[Journal]
Storage=persistent
Compress=yes
SystemMaxUse=250M
SystemKeepFree=1G
SystemMaxFileSize=25M
RuntimeMaxUse=50M
RuntimeMaxFileSize=10M
MaxFileSec=1day
MaxRetentionSec=14day
RateLimitIntervalSec=30s
RateLimitBurst=10000
